package app.berilo.reader.translate.prompts

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * Reader for the committed cross-language prompt vectors.
 *
 * `src/test/resources/prompts/python_prompts.json` is generated by evaluating the real
 * `berilo.prompts` module (every registered [TranslationStyle]'s prompt strings, its
 * `promptDigest`, and the shared `STRICT_MARKER_CLAUSE`) and committing the result — the same
 * pattern `IdentityFixtures` uses for the segment-identity golden fixtures. `PromptTextTest`
 * diffs this port against it, so a transcription slip in a prompt string fails a test instead of
 * silently shipping a tablet that translates under the same version string as a different
 * prompt.
 */
object PromptVectors {
    private val JSON = Json { ignoreUnknownKeys = false }

    /** Parse the committed vector file. */
    fun load(): PythonPromptVectorFile =
        JSON.decodeFromString(PythonPromptVectorFile.serializer(), readText())

    private fun readText(): String =
        requireNotNull(
            PromptVectors::class.java.getResourceAsStream("/prompts/python_prompts.json"),
        ) { "Missing fixture prompts/python_prompts.json — regenerate from berilo.prompts" }
            .use { it.readBytes().toString(Charsets.UTF_8) }
}

/** Every prompt string and digest the real `berilo.prompts` module produced. */
@Serializable
data class PythonPromptVectorFile(
    val strictMarkerClause: String,
    val styles: List<PythonStyleVector>,
)

/** One style's prompt strings and identity, as Python computed them. */
@Serializable
data class PythonStyleVector(
    val name: String,
    val version: String,
    val batchSystem: String,
    val strictSystem: String,
    val singleSystem: String,
    val bookContextSystem: String? = null,
    val reviseSystem: String? = null,
    val reviseStrictSystem: String? = null,
    val targetLangs: List<String>? = null,
    val promptDigest: String,
)
