package app.berilo.reader.translate.model

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test

/**
 * Tests [Glossary] and [glossaryIdentity] against `berilo.glossary`'s behaviour.
 *
 * The cross-language vectors in [`glossaryIdentity agrees with Python`] were generated by
 * running `python3 -c "from berilo.glossary import Glossary, glossary_identity; ..."` against
 * this worktree's `translator/berilo/glossary.py` (A2) for each fixed term map below — the same
 * "commit Python-generated digests as test vectors" recipe B1a used for segment identity.
 */
class GlossaryTest {

    @Test
    fun `an empty glossary renders an empty prompt block`() {
        assertEquals("", Glossary(emptyMap()).toPromptBlock())
        assertEquals(true, Glossary(emptyMap()).isEmpty())
    }

    @Test
    fun `toPromptBlock sorts terms by source, not by map order`() {
        val glossary = Glossary(linkedMapOf("Shire" to "Shire", "Frodo" to "Frodo", "Gandalf" to "Gandalf"))

        val block = glossary.toPromptBlock()

        val expected =
            "GLOSSARY (use these fixed renderings for the following terms; " +
                "inflect/decline them naturally as the target language requires):\n" +
                "- Frodo -> Frodo\n" +
                "- Gandalf -> Gandalf\n" +
                "- Shire -> Shire"
        assertEquals(expected, block)
    }

    @Test
    fun `glossaryIdentity is insertion-order independent`() {
        val forward = Glossary(linkedMapOf("Frodo" to "Frodo", "Shire" to "Shire", "Gandalf" to "Gandalf"))
        val reordered = Glossary(linkedMapOf("Gandalf" to "Gandalf", "Shire" to "Shire", "Frodo" to "Frodo"))

        assertEquals(glossaryIdentity(forward), glossaryIdentity(reordered))
    }

    @Test
    fun `null and an empty glossary share one identity`() {
        assertEquals(glossaryIdentity(null), glossaryIdentity(Glossary(emptyMap())))
    }

    @Test
    fun `a non-empty glossary has a different identity from the empty one`() {
        assertNotEquals(glossaryIdentity(null), glossaryIdentity(Glossary(mapOf("brook" to "potok"))))
    }

    @Test
    fun `two glossaries with different terms have different identities`() {
        val a = Glossary(mapOf("brook" to "potok"))
        val b = Glossary(mapOf("brook" to "reka"))

        assertNotEquals(glossaryIdentity(a), glossaryIdentity(b))
    }

    /**
     * Digests generated by Python for four fixed term maps, committed as test vectors
     * (`docs/findings.md`'s cross-language gate). Mutation-proof: unsorting
     * [Glossary.toPromptBlock]'s renderer (dropping `sorted()`) changes `terms.keys` iteration
     * to Kotlin's `LinkedHashMap` insertion order, which for the ASCII vector below (declared
     * out of sorted order: Shire, Frodo, Gandalf) would render a different block and therefore
     * a different digest from Python's sorted rendering — turning this test red.
     */
    @Test
    fun `glossaryIdentity agrees with Python for fixed term maps, including non-ASCII`() {
        val ascii = Glossary(linkedMapOf("Shire" to "Shire", "Frodo" to "Frodo", "Gandalf" to "Gandalf"))
        assertEquals("8d8a2f1688dc310f6b8678b28a4db93d993bb88a", glossaryIdentity(ascii))

        val nonAscii =
            Glossary(
                linkedMapOf(
                    "Ljubljana" to "Ljubljana",
                    "Šiška" to "Šiška",
                    "Čatež" to "Čatež",
                    "Žale" to "Žale",
                ),
            )
        assertEquals("6f83e5a0418470bf26d26490fd5e6998329f2629", glossaryIdentity(nonAscii))

        val single = Glossary(mapOf("brook" to "potok"))
        assertEquals("daf59ea9d386127c0ed187aa34f24cd511e114fa", glossaryIdentity(single))

        assertEquals("da39a3ee5e6b4b0d3255bfef95601890afd80709", glossaryIdentity(Glossary(emptyMap())))
        assertEquals("da39a3ee5e6b4b0d3255bfef95601890afd80709", glossaryIdentity(null))
    }
}
