package app.berilo.reader.translate.model

import java.security.MessageDigest
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals

/**
 * Reader and assertions for the cross-language identity fixtures.
 *
 * The fixtures are generated by `python3 -m berilo.identity_fixture` from the real example books
 * and committed under `src/test/resources/identity/`. They carry **no book text** — `data/` is
 * gitignored because those books are copyrighted — only derived identity: sha1 digests, counts
 * and structural indices.
 *
 * [assertMatchesFixture] is deliberately written against a [Book], not against the fixture's own
 * ids: today the only real [Book] this suite can build is the synthetic one, but B2's EPUB reader
 * produces exactly the same type. When it lands, the real-book test tightens from
 * "the fixture is self-consistent" to a full round trip by passing the reader's output to this
 * same function — no fixture-format change, no new assertions.
 */
object IdentityFixtures {

    /** Fixture slugs of the four real example books, in the order the plan tabulates them. */
    val EXAMPLE_SLUGS = listOf("new-rules-of-war", "revenge-of-geography", "sandworm", "ember-spark")

    /** Shape version the generator writes; a bump here must be a deliberate port change. */
    const val EXPECTED_FIXTURE_VERSION = 1

    private val JSON = Json { ignoreUnknownKeys = false }

    /**
     * Read a fixture file's raw text off the unit-test classpath.
     *
     * @param name File name under `identity/`.
     * @return The file contents.
     */
    fun readText(name: String): String =
        requireNotNull(IdentityFixtures::class.java.getResourceAsStream("/identity/$name")) {
            "Missing fixture identity/$name — regenerate with python3 -m berilo.identity_fixture"
        }
            .use { it.readBytes().toString(Charsets.UTF_8) }

    /**
     * Load and parse an identity fixture.
     *
     * @param slug Fixture slug, e.g. `sandworm`.
     * @return The parsed fixture.
     */
    fun loadIdentity(slug: String): IdentityFixture =
        JSON.decodeFromString(IdentityFixture.serializer(), readText("$slug.identity.json"))

    /**
     * Load and parse the `make_segment_id` / `segment_hash` probe vectors.
     *
     * @return The parsed vector fixture.
     */
    fun loadVectors(): VectorFixture =
        JSON.decodeFromString(VectorFixture.serializer(), readText("segment_id_vectors.json"))

    /**
     * Hex-encode the sha1 digest of raw bytes, for image identity.
     *
     * @param bytes The bytes to hash.
     * @return A 40-character lowercase hexadecimal digest.
     */
    fun sha1Hex(bytes: ByteArray): String =
        MessageDigest.getInstance("SHA-1").digest(bytes).joinToString("") { "%02x".format(it) }

    /**
     * Assert that a book reproduces a fixture's identity, segment for segment.
     *
     * Every id is *recomputed* from `(chapterIndex, position, text)` rather than read off the
     * book, so a book whose ids were copied from somewhere else cannot pass.
     *
     * @param book The book under test.
     * @param fixture The committed fixture it must match.
     */
    fun assertMatchesFixture(book: Book, fixture: IdentityFixture) {
        assertEquals("fixture_version", EXPECTED_FIXTURE_VERSION, fixture.fixtureVersion)
        assertEquals("language", fixture.language, book.language)
        assertEquals("source_format", fixture.source.format, book.sourceFormat)
        assertEquals("segment count", fixture.segmentCount, book.segments.size)
        assertEquals("segment rows", fixture.segmentCount, fixture.segments.size)
        assertEquals("chapter count", fixture.chapterCount, book.chapterCount)
        assertEquals("image count", fixture.imageCount, book.images.size)

        book.segments.forEachIndexed { index, segment ->
            val expected = fixture.segments[index]
            val where = "segment[$index]"
            assertEquals("$where chapter_index", expected.chapterIndex, segment.chapterIndex)
            assertEquals("$where position", expected.position, segment.position)
            assertEquals("$where type", expected.type, segment.type)
            assertEquals("$where heading_level", expected.headingLevel, segment.headingLevel)
            assertEquals("$where id", expected.id, segment.id)
            assertEquals(
                "$where recomputed id",
                expected.id,
                makeSegmentId(segment.chapterIndex, segment.position, segment.text),
            )
            assertEquals("$where segment_hash", expected.segmentHash, segmentHash(segment.text))
        }

        book.images.forEachIndexed { index, image ->
            val expected = fixture.images[index]
            val where = "image[$index]"
            assertEquals("$where id", expected.id, image.id)
            assertEquals("$where media_type", expected.mediaType, image.mediaType)
            assertEquals("$where chapter_index", expected.chapterIndex, image.chapterIndex)
            assertEquals("$where anchor", expected.anchorSegmentId, image.anchorSegmentId)
            assertEquals("$where data_sha1", expected.dataSha1, sha1Hex(image.data))
        }

        assertEquals("book_hash", fixture.bookHash, bookHash(book))
    }
}

/** One book's committed identity: counts, ordered segment ids, image anchors — never text. */
@Serializable
data class IdentityFixture(
    @SerialName("fixture_version") val fixtureVersion: Int,
    val source: FixtureSource,
    val language: String,
    @SerialName("book_hash") val bookHash: String,
    @SerialName("segment_count") val segmentCount: Int,
    @SerialName("chapter_count") val chapterCount: Int,
    @SerialName("image_count") val imageCount: Int,
    val segments: List<FixtureSegment>,
    val images: List<FixtureImage> = emptyList(),
)

/** Which book a fixture describes, by slug — never by its on-disk filename. */
@Serializable
data class FixtureSource(val slug: String, val format: String)

/** One segment's derived identity. */
@Serializable
data class FixtureSegment(
    @SerialName("chapter_index") val chapterIndex: Int,
    val position: Int,
    val type: SegmentType,
    @SerialName("heading_level") val headingLevel: Int? = null,
    val id: String,
    @SerialName("segment_hash") val segmentHash: String,
)

/** One image resource's derived identity; the bytes appear only as their digest. */
@Serializable
data class FixtureImage(
    val id: String,
    @SerialName("media_type") val mediaType: String,
    @SerialName("chapter_index") val chapterIndex: Int,
    @SerialName("anchor_segment_id") val anchorSegmentId: String? = null,
    @SerialName("data_sha1") val dataSha1: String,
)

/** Python-computed `make_segment_id` / `segment_hash` probe vectors. */
@Serializable
data class VectorFixture(
    @SerialName("fixture_version") val fixtureVersion: Int,
    val vectors: List<IdVector>,
)

/** One probe vector: the inputs, and the digests Python produced for them. */
@Serializable
data class IdVector(
    @SerialName("chapter_index") val chapterIndex: Int,
    val position: Int,
    val text: String,
    val id: String,
    @SerialName("segment_hash") val segmentHash: String,
)
