package app.berilo.reader.screenshot

import java.io.File
import org.junit.Assume

/**
 * S2.10: two device qualifiers all screenshot tests render at, standing in for the two
 * physical devices this app targets (docs/project_plan.md S2.10, S2.9's Verify line). There
 * is no emulator or attached Boox on this box, so these are Robolectric device qualifier
 * strings (`@Config(qualifiers = ...)`), not real device profiles — see `docs/findings.md`.
 */
internal object ScreenshotQualifiers {
    /**
     * A representative modern phone, matching Roborazzi's own `RobolectricDeviceQualifiers`
     * bundled defaults (Pixel-class: 411x914dp @ 420dpi, portrait).
     */
    const val PHONE = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"

    /**
     * Boox Tab Ultra: 1404x1872 physical px @ 227 dpi (the story's own spec). Robolectric
     * qualifiers are dp, not px: dp = px * 160 / dpi, so 1404px -> ~990dp, 1872px -> ~1319dp.
     * ~10.3" diagonal at a 4:3-ish aspect ratio, so "xlarge-notlong" (matching Robolectric's
     * own Nexus9/PixelTablet qualifier buckets), with the exact 227dpi spelled out rather than
     * a density bucket name so the physical dot pitch is reproduced, not just approximated.
     */
    const val BOOX_TAB_ULTRA = "w990dp-h1319dp-xlarge-notlong-notround-any-227dpi-keyshidden-nonav"
}

/**
 * Where the harness writes PNGs: `android/app/build/outputs/roborazzi/s2.10/` — under the
 * `build/` tree that `android/.gitignore` already excludes wholesale, never committed. The
 * harness (this file plus the ScreenshotTest classes) is the committed artifact; the PNGs are
 * disposable run output, regenerated by the `screenshots` Gradle task.
 */
internal object ScreenshotOutput {
    private val ROOT_DIR = File("build/outputs/roborazzi/s2.10")

    /** Deterministic, human-readable file name: `<surface>_<width>_<theme>.png`. */
    fun file(surface: String, width: String, theme: String): File {
        ROOT_DIR.mkdirs()
        return File(ROOT_DIR, "${surface}_${width}_${theme}.png")
    }

    /**
     * Roborazzi's `captureRoboImage` is a silent no-op — the call returns normally, writing
     * nothing — unless this system property is `"true"` (normally set by Roborazzi's own
     * Gradle plugin, which this project doesn't apply; the `screenshots` task in
     * app/build.gradle.kts sets it explicitly instead). Without a guard, every render() would
     * report "passed" on a plain `./gradlew test` run while writing zero PNGs — exactly the
     * silent-gate failure mode CLAUDE.md §9 warns about for caches/gates that can't see the
     * thing they certify.
     */
    private const val RECORD_PROPERTY = "roborazzi.test.record"

    /**
     * Skips the test (JUnit `Assume` — reported as "skipped", never "passed") when Roborazzi
     * isn't in record mode, so a plain `./gradlew test` (no [RECORD_PROPERTY]) stays green
     * without ever claiming a screenshot was written and reviewed. Call this before composing
     * any content, so the skip is cheap and unambiguous.
     */
    fun assumeRecording() {
        Assume.assumeTrue(
            "Skipping: -D$RECORD_PROPERTY=true not set (run the `screenshots` Gradle task, " +
                "not plain `test`/`testDebugUnitTest` — captureRoboImage() would otherwise " +
                "silently write nothing and this test would misreport PASSED).",
            System.getProperty(RECORD_PROPERTY) == "true",
        )
    }

    /**
     * Fails loudly, naming the file and the property, if a capture that should have run (see
     * [assumeRecording]) didn't actually produce a non-empty PNG. Every `render()` helper
     * calls this right after `captureRoboImage` — "passed" must never mean "wrote nothing".
     */
    fun assertCaptured(file: File) {
        assert(file.exists() && file.length() > 0L) {
            "captureRoboImage did not write ${file.path} (missing or empty) even though " +
                "-D$RECORD_PROPERTY=true was set, so this is a real capture failure, not a " +
                "skip — check the Roborazzi/Robolectric setup, not this assertion."
        }
    }
}
