package app.berilo.reader.screenshot

import java.io.File

/**
 * S2.10: two device qualifiers all screenshot tests render at, standing in for the two
 * physical devices this app targets (docs/project_plan.md S2.10, S2.9's Verify line). There
 * is no emulator or attached Boox on this box, so these are Robolectric device qualifier
 * strings (`@Config(qualifiers = ...)`), not real device profiles — see `docs/findings.md`.
 */
internal object ScreenshotQualifiers {
    /**
     * A representative modern phone, matching Roborazzi's own `RobolectricDeviceQualifiers`
     * bundled defaults (Pixel-class: 411x914dp @ 420dpi, portrait).
     */
    const val PHONE = "w411dp-h914dp-normal-long-notround-any-420dpi-keyshidden-nonav"

    /**
     * Boox Tab Ultra: 1404x1872 physical px @ 227 dpi (the story's own spec). Robolectric
     * qualifiers are dp, not px: dp = px * 160 / dpi, so 1404px -> ~990dp, 1872px -> ~1319dp.
     * ~10.3" diagonal at a 4:3-ish aspect ratio, so "xlarge-notlong" (matching Robolectric's
     * own Nexus9/PixelTablet qualifier buckets), with the exact 227dpi spelled out rather than
     * a density bucket name so the physical dot pitch is reproduced, not just approximated.
     */
    const val BOOX_TAB_ULTRA = "w990dp-h1319dp-xlarge-notlong-notround-any-227dpi-keyshidden-nonav"
}

/**
 * Where the harness writes PNGs: `android/app/build/outputs/roborazzi/s2.10/` — under the
 * `build/` tree that `android/.gitignore` already excludes wholesale, never committed. The
 * harness (this file plus the ScreenshotTest classes) is the committed artifact; the PNGs are
 * disposable run output, regenerated by the `screenshots` Gradle task.
 */
internal object ScreenshotOutput {
    private val ROOT_DIR = File("build/outputs/roborazzi/s2.10")

    /** Deterministic, human-readable file name: `<surface>_<width>_<theme>.png`. */
    fun file(surface: String, width: String, theme: String): File {
        ROOT_DIR.mkdirs()
        return File(ROOT_DIR, "${surface}_${width}_${theme}.png")
    }
}
