package app.berilo.reader.translate.epub

import app.berilo.reader.translate.model.Book
import app.berilo.reader.translate.model.bookFromJson
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

/**
 * The committed cross-language reference for [EpubWriter], generated by CPython.
 *
 * `android/tools/generate_assemble_vectors.py` runs `berilo.assemble.build_epub` over a handful
 * of **synthetic** books — nothing from the copyrighted `data/` corpus — and records the
 * sha256 of each archive, one record per zip entry, and the decoded text of every text entry.
 * The Kotlin writer has to reproduce all three, byte for byte.
 *
 * The archives themselves are deliberately **not** committed: a vector describes an EPUB
 * without being one, so the same gate runs in CI, in a fresh worktree, and on a machine that
 * has never seen a book.
 *
 * Regenerate after any change to `assemble.py`:
 * ```
 * PYTHONPATH=translator python3 android/tools/generate_assemble_vectors.py
 * ```
 */
internal object AssembleVectors {

    /** Vector shape this reader understands; a generator that moves on fails loudly here. */
    const val SUPPORTED_VERSION = 1

    private const val RESOURCE = "/epub/python_assemble.json"

    private val JSON = Json { ignoreUnknownKeys = true }

    /** One `uuid.uuid5` probe. */
    @Serializable
    data class Uuid5Case(val namespace: String, val name: String, val uuid: String)

    /** One zip entry as `zipfile` reported it. */
    @Serializable
    data class EntryRecord(
        val name: String,
        val method: String,
        val crc32: String,
        val size: Int,
        @SerialName("compressed_size") val compressedSize: Int,
    )

    /** One whole-archive case: the book that went in, and every byte-level fact that came out. */
    @Serializable
    data class Case(
        val name: String,
        @SerialName("book_resource") val bookResource: String? = null,
        @SerialName("book") val bookJson: JsonObject? = null,
        @SerialName("source_book") val sourceBookJson: JsonObject? = null,
        val bilingual: Boolean = false,
        val sha256: String,
        val size: Int,
        val entries: List<EntryRecord>,
        val documents: Map<String, String>,
    ) {
        /** The book to render: either inline in the vector, or a referenced test resource. */
        fun book(): Book =
            bookJson?.let { bookFromJson(it.toString()) }
                ?: bookFromJson(readResource("/" + requireNotNull(bookResource)))

        /** The aligned source book for a bilingual case, or `null`. */
        fun sourceBook(): Book? = sourceBookJson?.let { bookFromJson(it.toString()) }
    }

    @Serializable
    private data class Vector(
        val version: Int,
        @SerialName("id_namespace") val idNamespace: String,
        val uuid5: List<Uuid5Case>,
        val cases: List<Case>,
    )

    private val vector: Vector by lazy {
        val parsed = JSON.decodeFromString(Vector.serializer(), readResource(RESOURCE))
        check(parsed.version == SUPPORTED_VERSION) {
            "python_assemble.json is version ${parsed.version}, this reader understands " +
                "$SUPPORTED_VERSION — regenerate the port, not just the vector"
        }
        parsed
    }

    /** The namespace UUID `_book_identifier` derives every `dc:identifier` under. */
    val idNamespace: String get() = vector.idNamespace

    /** Every `uuid.uuid5` probe. */
    val uuid5Cases: List<Uuid5Case> get() = vector.uuid5

    /** Every whole-archive case. */
    val cases: List<Case> get() = vector.cases

    /** Look one case up by name, failing loudly rather than silently testing nothing. */
    fun case(name: String): Case =
        requireNotNull(cases.firstOrNull { it.name == name }) { "no vector case named $name" }

    private fun readResource(path: String): String =
        requireNotNull(AssembleVectors::class.java.getResourceAsStream(path)) {
            "missing test resource $path"
        }.use { it.readBytes().toString(Charsets.UTF_8) }
}
